[workspace]
members=["crates/*"]
default-members=[".", "crates/tinywasm", "crates/types", "crates/parser"]
resolver="2"

[profile.wasm]
opt-level="s"
lto="thin"
codegen-units=1
panic="abort"
inherits="release"

[workspace.package]
version="0.4.1"
edition="2021"
license="MIT OR Apache-2.0"
authors=["Henry Gressmann <mail@henrygressmann.de>"]
repository="https://github.com/explodingcamera/tinywasm"

[package]
name="tinywasm-root"
publish=false
edition="2021"

[[example]]
name="wasm-rust"
test=false

[dev-dependencies]
color-eyre="0.6"
tinywasm={path="crates/tinywasm", features=["unsafe"]}
wat={version="1.0"}

[profile.bench]
opt-level=3
lto="thin"
codegen-units=1
debug=true

[patch.crates-io]
# https://github.com/servo/pathfinder/pull/548
pathfinder_simd={git="https://github.com/servo/pathfinder", rev="e4fcda0d5259d0acf902aee6de7d2501f2bd6629"}
